In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('database.csv')
df

,Name,Batery,Acceleration,TopSpeed,Range,Efficiency,NumberofSeats,PriceinEurope
0,Nissan Leaf,36 kWh,7.9 sec,144 km/h,220 km,164 Wh/km,5,"€29,990"
1,Porsche Taycan Turbo S,83.7 kWh,2.8 sec,260 km/h,390 km,215 Wh/km,4,"€186,336"
2,Nissan e-NV200 Evalia,36 kWh,14.0 sec,123 km/h,165 km,218 Wh/km,7,"€43,433"
3,Volkswagen ID.3 Pure Performance,45 kWh,8.9 sec,160 km/h,275 km,164 Wh/km,5,"€31,960"
4,BMW iX3,74 kWh,6.8 sec,180 km/h,385 km,192 Wh/km,5,"€66,300"
...,...,...,...,...,...,...,...,...
122,BMW i4 M50,80.7 kWh,3.9 sec,225 km/h,450 km,179 Wh/km,5,"€69,900"
123,Volvo XC40 Recharge Twin Pure Electric,75 kWh,4.9 sec,180 km/h,340 km,221 Wh/km,5,"€59,250"
124,Renault Megane E-Tech Electric,60 kWh,8.0 sec,160 km/h,335 km,179 Wh/km,5,"€38,000"
125,Peugeot e-Rifter Standard 50 kWh,45 kWh,11.7 sec,135 km/h,200 km,225 Wh/km,7,"€37,590"
126,Peugeot e-Rifter Long 50 kWh,45 kWh,11.7 sec,135 km/h,195 km,231 Wh/km,7,"€42,590"

In [41]:
df = df.drop(['Battery kwh_norm', 'Acceleration sec_norm', 'TopSpeed km/h_norm', 'Range km_norm', 
              'Efficiency Wh/km_norm', 'NumberofSeats_norm', 'PriceinEurope_norm'], axis=1)
df

,Name,Battery kwh,Acceleration sec,TopSpeed km/h,Range km,Efficiency Wh/km,NumberofSeats,PriceinEurope,Score
0,Nissan Leaf,36,7,144,220,164,5,29990,0.416888
1,Porsche Taycan Turbo S,83,2,260,390,215,4,186336,0.407439
2,Nissan e-NV200 Evalia,36,14,123,165,218,7,43433,0.314064
3,Volkswagen ID.3 Pure Performance,45,8,160,275,164,5,31960,0.433198
4,BMW iX3,74,6,180,385,192,5,66300,0.458576
...,...,...,...,...,...,...,...,...,...
122,BMW i4 M50,80,3,225,450,179,5,69900,0.518974
123,Volvo XC40 Recharge Twin Pure Electric,75,4,180,340,221,5,59250,0.446292
124,Renault Megane E-Tech Electric,60,8,160,335,179,5,38000,0.445022
125,Peugeot e-Rifter Standard 50 kWh,45,11,135,200,225,7,37590,0.353284
126,Peugeot e-Rifter Long 50 kWh,45,11,135,195,231,7,42590,0.344236

In [42]:
df.to_csv('database.csv', index=False)