In [45]:
import pandas as pd

In [47]:
df = pd.read_csv('database.csv')
df

,Name,Batery,Acceleration,TopSpeed,Range,Efficiency,NumberofSeats,PriceinEurope
0,Nissan Leaf,36 kWh,7.9 sec,144 km/h,220 km,164 Wh/km,5,29990
1,Porsche Taycan Turbo S,83.7 kWh,2.8 sec,260 km/h,390 km,215 Wh/km,4,186336
2,Nissan e-NV200 Evalia,36 kWh,14.0 sec,123 km/h,165 km,218 Wh/km,7,43433
3,Volkswagen ID.3 Pure Performance,45 kWh,8.9 sec,160 km/h,275 km,164 Wh/km,5,31960
4,BMW iX3,74 kWh,6.8 sec,180 km/h,385 km,192 Wh/km,5,66300
...,...,...,...,...,...,...,...,...
122,BMW i4 M50,80.7 kWh,3.9 sec,225 km/h,450 km,179 Wh/km,5,69900
123,Volvo XC40 Recharge Twin Pure Electric,75 kWh,4.9 sec,180 km/h,340 km,221 Wh/km,5,59250
124,Renault Megane E-Tech Electric,60 kWh,8.0 sec,160 km/h,335 km,179 Wh/km,5,38000
125,Peugeot e-Rifter Standard 50 kWh,45 kWh,11.7 sec,135 km/h,200 km,225 Wh/km,7,37590
126,Peugeot e-Rifter Long 50 kWh,45 kWh,11.7 sec,135 km/h,195 km,231 Wh/km,7,42590

In [60]:
df = df.reset_index(drop=True)
df

,Name,Battery_kWh,Acceleration_sec,TopSpeed_kmh,Range_km,Efficiency_Whkm,NumberofSeats,PriceinEurope,Score
0,Smart EQ fortwo coupe,16.7,11.6,130.0,100.0,167.0,2,18460,0.319694
1,Smart EQ forfour,16.7,12.7,130.0,95.0,176.0,4,19120,0.317968
2,Smart EQ fortwo cabrio,16.7,11.9,130.0,95.0,176.0,2,21720,0.307582
3,Fiat 500e Hatchback 24 kWh,23.8,9.5,135.0,165.0,144.0,4,23560,0.385089
4,Fiat 500e Hatchback 42 kWh,37.3,9.0,150.0,250.0,149.0,4,27560,0.418001
...,...,...,...,...,...,...,...,...,...
122,Porsche Taycan Turbo,83.7,3.2,260.0,400.0,209.0,4,153016,0.429487
123,Porsche Taycan Turbo Cross Turismo,83.7,3.3,250.0,385.0,217.0,4,154444,0.415777
124,Porsche Taycan Turbo S,83.7,2.8,260.0,390.0,215.0,4,186336,0.402250
125,Porsche Taycan Turbo S Cross Turismo,83.7,2.9,250.0,380.0,220.0,4,187746,0.391977
126,Tesla Roadster,200.0,2.1,410.0,970.0,206.0,4,215000,0.666952

In [61]:
df.to_csv('database.csv', index=False)